name = "milad-vip"
main = "_worker.js"
compatibility_date = "2026-07-01"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "3105d0bed1cf427d92b8f6b3dc84910f"				#KV数据库id
