name = "milad-vip"
main = "_worker.js"
compatibility_date = "2026-07-01"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "b041ae7908214e35b4d6cdb9f1ed133d"				#KV数据库id
